#
# https://github.com/zcarfield/v2ray-bwg
#
# Copyright (c) 2020 zcarfield
#

name: Bandwagon - V2Ray

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 0 21 * * 5

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BWG_HOST: ${{ secrets.BWG_HOST }}
      BWG_USER: ${{ secrets.BWG_USER }}
      BWG_PWD: ${{ secrets.BWG_PWD }}
      BWG_SSH_PORT: ${{ secrets.BWG_SSH_PORT }}
      BWG_V2_PORT: ${{ secrets.BWG_V2_PORT }}
      V2_UUID: ${{ secrets.V2_UUID }}
      V2_WS_PATH: ${{ secrets.V2_WS_PATH }}
      CMD_PROMPT: ${BWG_USER}:${BWG_PWD}@${BWG_HOST}:${BWG_SSH_PORT} 

    steps:

    - name: Download Latest V2Ray
      run: |
        DOWNLOAD_URL="https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip"
        curl -fsSL "$DOWNLOAD_URL" -o "latest-v2ray.zip"
        unzip latest-v2ray.zip v2ray v2ctl geoip.dat geosite.dat
        rm latest-v2ray.zip
        chmod -v 755 v2*
        ./v2ray -version
    - name: Generate V2Ray Config File
      run: |
        base64 > config << EOF
        {
          "log": {
            "access": "none"
          },
          "inbounds": [
            {
              "port": 8080,
              "protocol": "vless",
              "settings": {
                "decryption": "none",
                "clients": [
                  {
                    "id": "${V2_UUID}"
                  }
                ]
              },
              "streamSettings": {
                "network":"ws",
                "wsSettings": {
                  "path": "${V2_WS_PATH}"
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom",
              "settings": {}
            }
          ]
        }
        EOF
        cat config | base64 -d > config.json
    - name: Generate V2ray.tar File
      run: |
        zip v2ray.zip v2ray v2ctl geoip.dat geosite.dat config.json
        ls -l v2ray.zip
        scp v2ray.zip 
    - name: Generate Manifest File
      run: |
        scp v2ray.zip ${CMD_PROMPT}:~/
        ssh ${CMD_PROMT} "ls -l"
